import "./globals.css";
import type { Metadata } from "next";
import React from "react";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

export const metadata: Metadata = {
  title:
    "Pediatric Orthopedic Specialists - Luskin Orthopaedic Institute for Children",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-arial block w-full bg-slate-200">
        <div className="w-full m-auto page-container bg-white">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
