import "./globals.css";
import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import SocialMediaBanner from "./components/SocialMediaBanner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:
    "Pediatric Orthopedic Specialists - Luskin Orthopaedic Institute for Children",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <SocialMediaBanner />
        <Footer />
      </body>
    </html>
  );
}
