import "./globals.css";
import type { Metadata } from "next";
import React from "react";
import Navbar from "@/app/components/NabarLayout/Navbar";
import Footer from "@/app/components/Footer";
import { GoogleAnalytics } from "@next/third-parties/google";
import Script from "next/script";

export const metadata: Metadata = {
  title:
    "Pediatric Orthopedic Specialists - Luskin Orthopaedic Institute for Children",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-arial block w-full bg-slate-200">
        <div className="w-full m-auto page-container bg-white">
          <Navbar />
          <div className="h-[166px]"></div>
          <main className="">{children}</main>
          <Footer />
        </div>
      </body>
      <GoogleAnalytics gaId="G-7HE98BYBD0" />
      <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></Script>
    </html>
  );
}
